url_login: https://test-stand.gb.ru/gateway/login
url_post: https://test-stand.gb.ru/api/posts
url: https://test-stand.gb.ru/gateway/posts
username: "JuanMay89"
password: "07711a5e5e"
title: "Фурина"
description: "Гидро архонт Фонтейна"
content: "Сильный персонаж водной стихии"